@startuml Create RentalCars

header Admin Create RentalCars

actor user
participant server <<javaScript>>
participant rentalCars <<router>>
participant rentalCars <<controllers>>
participant RentalCars <<models>>
participant rentalCarsDB <<MongoDB>>

user -> server : req.post('/rentalCars')
server -> rentalCars : app.use("/rentalCars", rentalCars)
alt is Admin
    rentalCars -> rentalCars : createRentalCars
    rentalCars -> RentalCars : create(req.body)
    RentalCars -> rentalCarsDB : RentalCarsSchema
    rentalCarsDB -> RentalCars : newRentalCars
    RentalCars -> rentalCars : newRentalCars
    rentalCars -> user : newRentalCars
else is not Admin
    rentalCars -> user : not authorized to access this route
end

@enduml
