@startuml

header Update Booking

actor user
participant server <<javaScript>>
participant bookings <<router>>
participant bookings. <<controllers>>
participant Booking <<models>>
participant hotelsDB <<MongoDB>>

user -> server : req.put('/bookings/:booking_id')
server -> bookings : app.use("/bookings", bookings)
bookings -> bookings. : updateBooking
bookings. -> Booking : findByIdAndUpdate(req.params.id, req.body)
Booking -> hotelsDB : BookingSchema
hotelsDB -> Booking : updatedBooking
Booking -> bookings. : updatedBooking
bookings. -> user : updatedBooking

@enduml
