@startuml Update RentalCar

header Admin Update RentalCar

actor user
participant server <<javaScript>>
participant rentalCars <<router>>
participant rentalCars <<controllers>>
participant RentalCar <<models>>
participant rentalCarsDB <<MongoDB>>

user -> server : req.put('/rentalCars/:id')
server -> rentalCars : app.use("/rentalCars", rentalCars)
alt is Admin
    rentalCars -> rentalCars : updateRentalCar
    rentalCars -> RentalCar : findByIdAndUpdate(req.params.id, req.body)
    RentalCar -> rentalCarsDB : RentalCarSchema
    rentalCarsDB -> RentalCar : updatedRentalCar
    RentalCar -> rentalCars : updatedRentalCar
    rentalCars -> user : updatedRentalCar
else is not Admin
    rentalCars -> user : not authorized to access this route
end

@enduml
